blueprint:
  name: Hue-style motion automation
  description: Turn lights on when motion is detected and below a set lux level, with daytime/nightime luminance level
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
        entity:
          domain: binary_sensor
          device_class: occupancy
    lux_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    lux_level:
      name: Illuminance level
      description: If lux is below this value and motion is detected, the light will turn on.
      default: 100
      selector:
        number:
          min: 0
          max: 1000
    light_target:
      name: Light
      selector:
        target:
          entity:
            multiple: true
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    transition_time:
      name: Transition time
      description: Time in seconds to reach desired state.
      default: 0
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: seconds 
    daytime_start:
      name: Daytime start
      description: Time of day at which daytime starts
      default: 08:00:00
      selector:
        time:
    daytime_light_level:
      name: Daytime light level
      description: Light level during daytime hours in percentage
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: percent
    nighttime_start:
      name: Nighttime start
      description: Time of day at which nighttime starts
      # there is a bug which considers 22:00:00 as incorrect but prepending 0 somehow works
      # https://github.com/home-assistant/frontend/issues/10822
      # This is not just for 2 digit time though, 8:00:00 also doesn't work, and had to be 08:00:00
      default: 022:00:00
      selector:
        time:
    nighttime_light_level:
      name: Nighttime light level
      description: Light level during nighttime hours in percentage
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: percent

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  numeric_state:
    entity_id: !input lux_entity
    below: !input lux_level

action:
  - choose:
    - conditions:
      - condition: template
        value.template: |-
          {{
            now().time() >= strptime( nighttime_start, time_fmt).time() and
            now().time() < strptime( daytime_start, time_fmt ).time()
          }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
            data:
              brightness_pct: !input nighttime_light_level
              transition: !input transition_time
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_target
        data:
          brightness_pct: !input daytime_light_level
          transition: !input transition_time

  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target:
      entity_id: !input light_target
    data:
      transition: !input transition_time
